Tmp_Login/config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  resources :articles
  resources :sessions
  
  root to: 'articles#index'
end

Tmp_Login/app/models/article.rb
class Article < ApplicationRecord
end

Tmp_Login/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

Tmp_Login/app/controllers/ create_users.rb
class CreateUsers < ActiveRecord::Migration
  def change
    create_table :users do |t|
      t.string :username 
      t.string :email
      t.string :encrypted_password 
      t.string :salt
      t.timestamps
    end
  end
end

Tmp_Login/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  private
  
  def logged_in?
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :logged_in?
end

Tmp_Login/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
   # render plain: "hi pankaj"
  @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(allowed_params)
      redirect_to @article, notice: 'Article has been updated'
    else
      render :edit
    end
  end
  
  private
  
  def allowed_params
    params.require(:article).permit(:name, :author, :content, :published_at)    
  end
end

Tmp_Login/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in! '
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

Tmp_Login/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(allowed_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Thank you for signing up!'
    else
      render :new
    end
  end
  private
  def allowed_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

Tmp_Login/app/helpers/sessions_helper.rb
module SessionsHelper
end

Tmp_Login/app/views/articles/_article.html.erb
<div class="info">
  by <%= article.author %>
  on <%= article.published_at.strftime('%b %d, %Y') %>
</div>
<div class="content"><%= article.content %></div>
<h2>
  <%= link_to "Go", article %>
</h2>

Tmp_Login/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :rows => 12, :cols => 35 %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

Tmp_Login/app/views/articles/index.html.erb
<h1>NIQ</h1>

<div id="articles">
<h1>this is NIQ team articles</h1>
<%= render @articles %>
</div>

Tmp_Login/app/views/articles/show.html.erb
<h1><%= @article.name %></h1>
<%= @article.content %>
<p>
  <%= link_to "Edit", edit_article_path(@article) %> |
  <%= link_to "Browse Articles", articles_path %>
</p>